### ISSUE TITLE
preloads not linked to parent span

### ISSUE THREAD

**Issue by dvic** [opentelemetry-beam/opentelemetry_ecto#15]
By default, Ecto executes preloads (if there are more than one) in parallel, e.g.,

```elixir
Repo.all(from(Demo.Post, preload: [:authors, :comments]))
```

or 

```elixir
Repo.all(Demo.Post)
|> Repo.preload([:authors, :comments])
```

This will result in the two queries for `authors` and `comments` not to be linked to the parent span.

One workaround for this is passing `in_parallel: false` to `Repo.all` or `Repo.preload`, but this might impact the performance.

Is this something we want to try to address? Or does this require changes in Ecto? In theory we could get the caller pid from the telemetry handler using `Process.get(:"$callers")` and do something with this.

**Comment by bryannaegele** [comment]
What is the parent span in this case? A span around the example blocks?

**Comment by tsloughter** [comment]
My guess is that changes are required to Ecto. I don't know enough about Ecto and its telemetry events to say for sure, but since it is spawning processes to run queries and I know it isn't passing a span context, it is a safe bet.

**Comment by tsloughter** [comment]
I assumed the parent or linked to span was one created when the Repo.all query is run.

**Comment by dvic** [comment]
> What is the parent span in this case? A span around the example blocks?

> I assumed the parent or linked to span was one created when the Repo.all query is run.

Yes exactly, linking the preloads in the first example to the span of the "root" query is not something I expect, linking it to the span that's set around the code block would already be awesome.

**Comment by bryannaegele** [comment]
This line is why

https://github.com/elixir-ecto/ecto/blob/78ba8713cf8f505688feac8ce524906cba3eb984/lib/ecto/repo/preloader.ex#L134

**Comment by tsloughter** [comment]
Right, Ecto would need to pass a context to the children.

**Comment by bryannaegele** [comment]
Tracing up the ancestors is potentially possible but you'd have to walk the list, fetch the dictionary from each, and check if there's a context. We've been trying to avoid that kind of stuff.

**Comment by dvic** [comment]
> Tracing up the ancestors is potentially possible but you'd have to walk the list, fetch the dictionary from each, and check if there's a context. We've been trying to avoid that kind of stuff.

If you do this in the telemetry callback for Ecto there is actually only a single element you have to consider (the last element in `$callers`, if there is one) but I get your point. On a side note: with *fetch the dictionary from each*, you mean the process dictionary? You can share this with another process? Or do you mean some ETS-based solution?

**Comment by bryannaegele** [comment]
AFAIK the parent pid is an option passed to the preloader according to https://github.com/elixir-ecto/ecto/blob/78ba8713cf8f505688feac8ce524906cba3eb984/lib/ecto/repo/preloader.ex#L131. I'm not sure where `$callers` that you're referring to is coming from. Can you elaborate on that?

If it's spawned from a task, the calling process is actually in the dictionary as `dictionary: [evaluator: #PID<0.105.0>]` and not ancestors.

> you mean the process dictionary? You can share this with another process?

Yes. Otel keeps the context in the pdict. The dictionary can't be shared but it can be fetched which results in a copy of its values.

**Comment by dvic** [comment]
> AFAIK the parent pid is an option passed to the preloader according to https://github.com/elixir-ecto/ecto/blob/78ba8713cf8f505688feac8ce524906cba3eb984/lib/ecto/repo/preloader.ex#L131.

Ah yes, but I'm afraid we don't have access to that in the telemetry callback. Reading that comment above it I'm not even sure how this solution would work with ecto sandbox in auto mode, but that's a problem for another time ;)

> I'm not sure where `$callers` that you're referring to is coming from. Can you elaborate on that?

It's a feature of `Task` as I understand it, added in https://github.com/elixir-lang/elixir/pull/8510.  I'm not sure if it's considered "public".

![image](https://user-images.githubusercontent.com/1214337/127387749-6ca574c7-da1c-4a0f-95b2-fce06345fdbb.png)

> Yes. Otel keeps the context in the pdict. The dictionary can't be shared but it can be fetched which results in a copy of its values.

Apologies for my lack of knowledge, but how do you do this actually? Is this a call in otel or something erlang specific?

**Comment by bryannaegele** [comment]
> Apologies for my lack of knowledge, but how do you do this actually?

`Process.info(pid, :dictionary)`
