### ISSUE TITLE
Release version 0.6 to Hex

### ISSUE THREAD

**Issue by sgerrand** [opentelemetry-beam/opentelemetry_ecto#18]
This package was updated to version 0.6 in 03a18a3e1585816751d2043780cf537d44c7756d but a version for this was never published to Hex. Can this version be published? There's only two versions of this package currently available on Hex: 0.1.0 and 1.0.0-rc.1. It would be helpful to be able to use a version between v0.1.0 from 18 months ago and a release candidate.

**Comment by bryannaegele** [comment]
You can safely upgrade to the 1.0-rc2 version of otel from 0.6. There are no API differences between the two afaik. That is why we never published a version between 0.4 and 1.0.

**Comment by sgerrand** [comment]
Thanks for those additional details, good to know that the API remains the same between those versions. To confirm, are you saying that you're not going to release v0.6 to Hex?

**Comment by bryannaegele** [comment]
I'm afraid not. It would be a lot of work for us at this point to go back and retroactively publish versions for all the instrumentation libraries for each pre-1.0 otel release.
