### ISSUE TITLE
Upgrade opentelemetry to version 0.5.0

### ISSUE THREAD

**Issue by GDegrove** [opentelemetry-beam/opentelemetry_ecto#6]
When trying to run both opentelemetry_ecto and opentelemetry_phoenix in an application, we get a dependencies error:

```
Failed to use "opentelemetry" (version 0.5.0) because
  apps/common/mix.exs requires ~> 0.5.0
  opentelemetry_ecto (version 0.1.0) requires ~> 0.4.0
  opentelemetry_phoenix (version 0.2.0) requires ~> 0.5.0

```

In order to use both, and have  this issue, is it possible to update the open_telemetry dependencies to version 0.5.0

**Comment by jinjagit** [comment]
This would be great. We are using opentelemetry_phoenix and encountered the same dependency error when trying to add this dependency.

**Comment by sgerrand** [comment]
👋 @tsloughter, are you able to assist with this request? It would help me out a lot as well.

**Comment by sgerrand** [comment]
To be clear, @GDegrove contributed the changes (❤️) in #7 and they're merged. What I'm really interested in is a new version of this module to be published to Hex, which is what @garthk asked for in #9.

**Comment by tsloughter** [comment]
When #12 is updated to 1.0.0-rc.1 I'll merge it and a release can be published.

**Comment by bryannaegele** [comment]
@GDegrove we're going to migrate this repo to https://github.com/open-telemetry/opentelemetry-erlang-contrib soon. Can you please sign the CNCF CLA so we can proceed?

https://identity.linuxfoundation.org/projects/cncf

Thank you!

**Comment by GDegrove** [comment]
Hello, 
 I totally forgot to continue the process once started, the process is ongoing, 

Regards,
Gil

**Comment by GDegrove** [comment]
@bryannaegele I think it's all set.
